[[constraint]]
  branch = "master"
  name = "github.com/atotto/clipboard"

[[constraint]]
  name = "github.com/dmulholl/janus-go"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/howeyc/gopass"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-wordwrap"

[[constraint]]
  name = "github.com/pelletier/go-toml"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/tonnerre/golang-text"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[prune]
  go-tests = true
  unused-packages = true
