name: "Build & Test"

on: [push, workflow_dispatch]

env:
  GO_VERSION: "1.21"

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run Test Suite
        run: make test-verbose
